name: socceroon
favicon: null
layout_spectrum: 0.8762266512494534
typography_spectrum: 0.479181723902002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8eaec3'
    - '#1a3c45'
    - '#0d0e12'
    - '#d5d3bc'
    - '#746e60'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
