name: socceroon
favicon: null
layout_spectrum: 0.8762266512494534
typography_spectrum: 0.479181723902002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2d3d7'
    - '#a6a4a7'
    - '#3d3c44'
    - '#13090a'
    - '#7a706f'
  brandStrength: 0.7077773353084922
  lightness: 0.11082672909833491
  saturation: 0.3619891668204218
  rhythmicContrast: 0.6065743351355195
purpose: []
