name: socceroon
favicon: null
layout_spectrum: 0.21156
typography_spectrum: 0.65818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e13'
    - '#5d93d1'
    - '#a9bdd5'
    - '#333335'
    - '#6d6a61'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
