name: socceroon
favicon: null
layout_spectrum: 0.93108
typography_spectrum: 0.65818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8eaec3'
    - '#1a3c45'
    - '#0d0e12'
    - '#d5d3bc'
    - '#746e60'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
